Final/src/main/java/com/kh/myapp/member/controller/MemberController.java
Final/src/main/java/com/kh/myapp/member/model/dao/MemberDao.java
Final/src/main/java/com/kh/myapp/member/model/service/MemberService.java
Final/src/main/resources/mapper/marketerSQL.xml
Final/src/main/webapp/WEB-INF/views/member/admin.jsp
Final/src/main/webapp/WEB-INF/views/member/loginFrm.jsp
Final/src/main/webapp/WEB-INF/views/member/memberManage.jsp

1/5
1. 최고관리자 페이지 사이드바에 공지사항 삭제
2. 최고관리자 판매자 관리에 판매자 회원 탈퇴 기능추가

최고관리자 페이지에서 판매자 탈퇴기능 구현[NOEL-24]

---

Final/src/main/java/com/kh/myapp/member/controller/MemberController.java
Final/src/main/java/com/kh/myapp/member/model/dao/MemberDao.java
Final/src/main/java/com/kh/myapp/member/model/service/MemberService.java
Final/src/main/resources/mapper/orderSQL.xml
Final/src/main/webapp/WEB-INF/views/market/orderAll.jsp
Final/src/main/webapp/WEB-INF/views/market/orderManagementView.jsp
Final/src/main/webapp/WEB-INF/views/market/orderPrd.jsp

판매자 마이페이지 > 주문관리에서 주문수량, 남은재고 값 수정

fix:[이주연] 판매자 마이페이지에서 상품별 주문내역 출력[NOEL-30]

---

Final/src/main/java/com/kh/myapp/cart/controller/CartController.java
Final/src/main/java/com/kh/myapp/member/controller/MemberController.java
Final/src/main/java/com/kh/myapp/member/model/service/MemberService.java
Final/src/main/resources/mapper/orderSQL.xml
Final/src/main/webapp/WEB-INF/views/market/orderAll.jsp
Final/src/main/webapp/WEB-INF/views/market/orderPrd.jsp
Final/src/main/webapp/WEB-INF/views/order/ordercart.jsp
Final/src/main/webapp/WEB-INF/views/order/ordercomplete.jsp

1. feat: [이주연]판매자 마이페이지 배송상태 지정[NOEL-35]
2. fix: [이주연] 판매자 마이페이지에서 상품별 주문내역 출력[NOEL-30]
3. 장바구니에서 결제로 넘어갈 떄 체크박스 UI 변경

feat:[이주연]판매자 마이페이지 배송상태 지정[NOEL-35]

---

Final/src/main/java/com/kh/myapp/member/controller/MemberController.java
Final/src/main/java/com/kh/myapp/member/model/dao/MemberDao.java
Final/src/main/java/com/kh/myapp/member/model/service/MemberService.java
Final/src/main/resources/mapper/orderSQL.xml
Final/src/main/webapp/WEB-INF/views/market/marketDetailView.jsp
Final/src/main/webapp/WEB-INF/views/market/orderAll.jsp
Final/src/main/webapp/WEB-INF/views/market/orderManagementView.jsp
Final/src/main/webapp/WEB-INF/views/market/orderPrd.jsp

1. feat:[이주연]판매자 마이페이지 주문상세 검색기능 추가 [NOEL-39]
2. fix:[이주연]판매자 마이페이지 배송상태 지정[NOEL-35]

feat:[이주연]판매자 마이페이지 주문상세 검색기능 추가 [NOEL-39]

---

Final/src/main/java/com/kh/myapp/HomeController.java
Final/src/main/webapp/WEB-INF/views/cart/cart.jsp
Final/src/main/webapp/WEB-INF/views/class/classDetail.jsp
Final/src/main/webapp/WEB-INF/views/home.jsp
Final/src/main/webapp/WEB-INF/views/market/marketDetailView.jsp
Final/src/main/webapp/WEB-INF/views/market/marketListFrm.jsp
Final/src/main/webapp/WEB-INF/views/market/marketerProductMypage.jsp
Final/src/main/webapp/WEB-INF/views/market/myPrdWishList.jsp
Final/src/main/webapp/WEB-INF/views/market/orderAll.jsp
Final/src/main/webapp/WEB-INF/views/market/orderManagementView.jsp
Final/src/main/webapp/WEB-INF/views/market/orderPrd.jsp
Final/src/main/webapp/WEB-INF/views/market/prd_add.jsp
Final/src/main/webapp/WEB-INF/views/market/prd_update.jsp
Final/src/main/webapp/WEB-INF/views/order/order.jsp
Final/src/main/webapp/WEB-INF/views/order/ordercart.jsp
Final/src/main/webapp/WEB-INF/views/order/ordercomplete.jsp
Final/src/main/webapp/resources/css/product/marketDetailView.css

1.style:[이주연]마켓 디테일뷰 UI 수정[NOEL-42]

style:[이주연]마켓 디테일뷰 UI 수정[NOEL-42]

---

Final/src/main/webapp/WEB-INF/views/market/marketDetailView.jsp
Final/src/main/webapp/WEB-INF/views/market/myPrdWishList.jsp
Final/src/main/webapp/WEB-INF/views/member/userOrderList.jsp
Final/src/main/webapp/resources/css/product/marketDetailView.css

1. 회원 주문관리 주문취소, 구매평작성 버튼 수정
2. 회원 주문관리, 위시리스트 푸터 이슈  해결
3. 마켓 상세페이지, 회원 주문관리 상품금액 '원' 추가

feat:[이정하] 회원 주문관리 UI 수정[NOEL-44]

---

Final/src/main/webapp/WEB-INF/views/member/userOrderList.jsp

fix:[이정하] 회원 주문관리 UI 수정[NOEL-44]

---

Final/src/main/java/com/kh/myapp/market/controller/MarketQnaController.java
Final/src/main/java/com/kh/myapp/market/model/dao/MarketQnaDAO.java
Final/src/main/java/com/kh/myapp/market/model/service/MarketQnaService.java
Final/src/main/java/com/kh/myapp/market/model/vo/MarketQnaVO.java
Final/src/main/resources/mapper/marketSQL.xml
Final/src/main/webapp/WEB-INF/views/market/qnaDetail.jsp
Final/src/main/webapp/resources/css/product/qnaDetail.css

1. 마켓 Qna 답변 기능 구현[NOEL-45]
2. noel_product_qna 수정된 테이블에 맞게 답변 등록, 삭제기능 재구현

마켓 Qna 답변 기능 구현[NOEL-45]

---

Final/src/main/java/com/kh/myapp/cl/model/vo/ClassImg.java
Final/src/main/webapp/WEB-INF/views/class/classUpdate.jsp
Final/src/main/webapp/resources/js/class/classUpdate.js

feat:[엄세연]클래스 정보 수정 기능 구현[NOEL-41]

feat:[엄세연]클래스 정보 수정 기능 구현[NOEL-41]

---

Final/src/main/java/com/kh/myapp/member/controller/MemberController.java
Final/src/main/resources/mapper/orderSQL.xml
Final/src/main/webapp/WEB-INF/views/member/userOrderList.jsp

1. 회원 마이페이지 주문내역에 구매평 작성 버튼 생성
2. 리뷰 작성시 데이터베이스 저장

feat:[차현오]회원 마이페이지 주문내역에 구매평 작성 버튼 활성화[NOEL-45]

---

Final/src/main/java/com/kh/myapp/member/controller/MemberController.java
Final/src/main/java/com/kh/myapp/member/model/dao/MemberDao.java
Final/src/main/java/com/kh/myapp/member/model/service/MemberService.java
Final/src/main/resources/mapper/marketSQL.xml
Final/src/main/webapp/WEB-INF/views/common/memberHeader.jsp
Final/src/main/webapp/WEB-INF/views/market/marketDetailView.jsp
Final/src/main/webapp/WEB-INF/views/member/memberQna.jsp
Final/src/main/webapp/resources/css/class/classList.css

1. 회원 마이페이지에서 본인이 작성한 qna만 출력[NOEL-53]
2. 클래스 메인페이지 상품 이미지 크기 조정

feat:[이정하] 회원 마이페이지에서 본인이 작성한 qna만 출력[NOEL-53]

---

Final/src/main/webapp/WEB-INF/views/member/userOrderList.jsp
Final/src/main/webapp/resources/css/product/marketDetailView.css

1. 일반회원 > 마이페이지 > 주문내역 배송중 일때 주문취소 버튼 비활성화
2. 일반회원 > 마이페이지 > 주문내역 버튼 ui 수정

fix:[이정하] 일반회원 마이페이지 주문내역 출력[NOEL-28]

---

Final/src/main/resources/mapper/classSQL.xml
Final/src/main/webapp/WEB-INF/views/class/classDetail.jsp
Final/src/main/webapp/WEB-INF/views/market/marketDetailView.jsp
Final/src/main/webapp/resources/css/class/classDetail.css
Final/src/main/webapp/resources/css/product/marketDetailView.css

1. 판매자가 마켓 상품 위시리스트 클릭 시 alert 창 팝업 수정
2. 마켓, 클래스 상세페이지 UI 수정

fix:[이정하] 판매자 일 때 장바구니, 구매하기, 위시리스트 클릭 시 alert창 [NOEL-31]

---

Final/src/main/webapp/WEB-INF/views/member/admin.jsp
Final/src/main/webapp/WEB-INF/views/member/checkId.jsp
Final/src/main/webapp/WEB-INF/views/member/joinFrm.jsp
Final/src/main/webapp/WEB-INF/views/member/loginFrm.jsp
Final/src/main/webapp/WEB-INF/views/member/marketerCheckId.jsp
Final/src/main/webapp/WEB-INF/views/member/marketerJoinFrm.jsp
Final/src/main/webapp/WEB-INF/views/member/marketerMypage.jsp
Final/src/main/webapp/WEB-INF/views/member/memberManage.jsp
Final/src/main/webapp/WEB-INF/views/member/mypage.jsp
Final/src/main/webapp/WEB-INF/views/member/searchIdFrm.jsp
Final/src/main/webapp/WEB-INF/views/member/searchIdResult.jsp
Final/src/main/webapp/WEB-INF/views/member/searchMemberFrm.jsp
Final/src/main/webapp/WEB-INF/views/member/searchPwFrm.jsp
Final/src/main/webapp/WEB-INF/views/member/sj.jsp
Final/src/main/webapp/WEB-INF/views/member/updateMarketerPw.jsp
Final/src/main/webapp/WEB-INF/views/member/updateMemberPw.jsp
Final/src/main/webapp/WEB-INF/views/member/updatePwSuccess.jsp
Final/src/main/webapp/resources/css/member/member.css
Final/src/main/webapp/resources/css/member/searchMember.css
Final/src/main/webapp/resources/css/member/updateMarketer.css

feat:[차현오]회원,판매자 CSS 및 UI조정[NOEL-58]

---

Final/src/main/java/com/kh/myapp/cl/controller/ClassController.java
Final/src/main/webapp/WEB-INF/views/class/classDetail.jsp
Final/src/main/webapp/WEB-INF/views/class/classListFrm.jsp
Final/src/main/webapp/WEB-INF/views/market/marketDetailView.jsp
Final/src/main/webapp/resources/css/class/classDetail.css
Final/src/main/webapp/resources/css/class/classList.css
Final/src/main/webapp/resources/css/product/marketDetailView.css

fix:[이주연] 클래스 결제 시 금액 이슈 해결[NOEL-60]
design:[이주연] 비회원 또는 판매자 일 때 마켓, 클래스의 예약 및 구매하기 클릭 시 alert창[NOEL-59]

fix:[이주연] 클래스 결제 시 금액 이슈 해결[NOEL-60],[NOEL-59]

---

Final/src/main/java/com/kh/myapp/market/model/vo/ProductVO.java
Final/src/main/resources/mapper/productSQL.xml
Final/src/main/webapp/WEB-INF/views/class/classDetail.jsp
Final/src/main/webapp/WEB-INF/views/class/classListFrm.jsp
Final/src/main/webapp/WEB-INF/views/market/marketDetailView.jsp
Final/src/main/webapp/WEB-INF/views/market/marketListFrm.jsp
Final/src/main/webapp/resources/css/class/classDetail.css
Final/src/main/webapp/resources/css/class/classList.css
Final/src/main/webapp/resources/css/product/marketDetailView.css

1. 마켓 상세페이지 ‘품절’ 버튼 구현 및 UI 수정
2. 클래스 디테일페이지 예약, 위시 버튼 UI 수정
3. 클래스 메인페이지 제목, BEST UI 수정

feat:[이정하] 마켓 상세페이지 ‘품절’ 버튼 구현[NOEL-6]

---

Final/src/main/java/com/kh/myapp/cl/model/vo/Class.java
Final/src/main/java/com/kh/myapp/cl/model/vo/Reserve.java
Final/src/main/resources/mapper/classSQL.xml
Final/src/main/resources/mapper/reserveSQL.xml
Final/src/main/webapp/WEB-INF/views/class/classDetail.jsp
Final/src/main/webapp/WEB-INF/views/class/reserveList.jsp
Final/src/main/webapp/resources/css/class/classDetail.css

1. 클래스 상세페이지 ‘오픈/클로즈’ 버튼 구현[NOEL-1]
2. 회원 마이페이지 예약내역탭 예약상태, 예약처리 구현 [NOEL-11]

feat:[이정하]클래스 상세페이지 ‘오픈/클로즈’ 버튼 구현 외 1건[NOEL-1, 11]

---

Final/src/main/java/com/kh/myapp/cl/model/dao/ClassDao.java
Final/src/main/webapp/WEB-INF/views/class/classDetail.jsp
Final/src/main/webapp/WEB-INF/views/class/reserveList.jsp
Final/src/main/webapp/WEB-INF/views/member/userOrderList.jsp
Final/src/main/webapp/resources/css/class/reserveList.css

1. 회원 마이페이지 예약내역탭 예약취소가 안되는 이슈 해결
2. 회원 마이페이지 예약내역탭 UI 수정 완료
3. reserveList.jsp 내 css 분리 (reserveList.css 추가)

fix:[이정하] 회원 마이페이지 예약내역탭 예약상태, 예약처리 구현 [NOEL-11]

---

Final/src/main/webapp/WEB-INF/views/aboutUs.jsp

aboutUs 내 grid-image 위치 가운데 처리

fix:[엄세연]aboutUs 페이지 구현[NOEL-67]

---

Final/src/main/java/com/kh/myapp/cl/controller/ClassController.java
Final/src/main/resources/mapper/classSQL.xml
Final/src/main/resources/mapper/reserveSQL.xml
Final/src/main/webapp/WEB-INF/views/class/classDetail.jsp
Final/src/main/webapp/WEB-INF/views/class/classListFrm.jsp
Final/src/main/webapp/WEB-INF/views/class/reserveManagement.jsp

판매자 > 클래스 예약 관리에 전체 판매자의 예약 내역이 뜨는 이슈 해결

fix:[엄세연]클래스 예약 리스트 출력 및 예약상태 변경 기능 구현[NOEL-49]

---

Final/src/main/resources/mapper/classSQL.xml
Final/src/main/webapp/WEB-INF/views/class/classUpdate.jsp

클래스 수정 시 인원, 휴무일, 주소, 영업시간 값 가져오기

fix:[엄세연]클래스 정보 수정 기능 구현[NOEL-41]

---

Final/src/main/webapp/WEB-INF/views/class/classDetail.jsp

메뉴가 몇 개든 가운데를 기준으로 정렬(한 줄에 최대 3개)

fix:[엄세연]클래스 상세페이지에 클래스 메뉴 출력[NOEL-26]

---

Final/src/main/java/com/kh/myapp/cl/controller/ClassController.java
Final/src/main/resources/mapper/classReviewSQL.xml
Final/src/main/webapp/WEB-INF/views/class/addMenuFrm.jsp
Final/src/main/webapp/WEB-INF/views/class/classAdd.jsp
Final/src/main/webapp/WEB-INF/views/class/classReviewAdd.jsp
Final/src/main/webapp/WEB-INF/views/class/classReviewUpdate.jsp
Final/src/main/webapp/WEB-INF/views/class/classUpdate.jsp
Final/src/main/webapp/WEB-INF/views/class/marketerClassMypage.jsp
Final/src/main/webapp/WEB-INF/views/class/menuFrm.jsp
Final/src/main/webapp/WEB-INF/views/class/reserveManagement.jsp
Final/src/main/webapp/WEB-INF/views/class/updateMenuFrm.jsp
Final/src/main/webapp/resources/css/class/menuList.css
Final/src/main/webapp/resources/css/class/reserveManagement.css

1. 클래스 메뉴 관리 페이지 UI 다른 페이지와 유사하게 수정
2. 파비콘 삽입
3. 안 쓰는 요소 정리
4. 클래스 리스트 내림차순으로 변경
5. 사용하지 않는 스타일 요소 삭제

style:[엄세연]클래스 파트 css 및 ui 조정[NOEL-71]

---

Final/src/main/webapp/WEB-INF/views/class/reserveList.jsp

1. 회원 > 마이페이지 > 예약내역 > '예약시간'을 '예약날짜(시간)'으로 수정

design:[이정하] 회원 마이페이지 예약내역탭 예약상태, 예약처리 구현 [NOEL-11]

---

Final/src/main/java/com/kh/myapp/member/controller/MemberController.java

https://www.notion.so/eddi-robot-academy/DB-1840162c936442ebb9a9a88fa2658c25
참조

feat:[차현오]회원 판매자 로그인시 DB안에 존재 하지 않을시 500에러 이슈[NOEL-73]

---

Final/src/main/webapp/WEB-INF/views/class/reserveList.jsp

feat:[차현오]회원 마이페이지 예약내역에 클래스 이름 클릭시 해당 클래스 디테일로 넘어감[NOEL-74]

---

Final/src/main/java/com/kh/myapp/market/controller/MarketController.java
Final/src/main/java/com/kh/myapp/market/model/dao/MarketReviewDAO.java
Final/src/main/java/com/kh/myapp/market/model/service/MarketReviewService.java
Final/src/main/java/com/kh/myapp/market/model/service/ProductService.java
Final/src/main/java/com/kh/myapp/market/model/vo/MarketReviewVO.java
Final/src/main/java/com/kh/myapp/market/model/vo/ProductVO.java
Final/src/main/java/com/kh/myapp/order/model/vo/OrderVO.java
Final/src/main/resources/mapper/marketSQL.xml
Final/src/main/resources/mapper/orderSQL.xml
Final/src/main/resources/mapper/productSQL.xml
Final/src/main/webapp/WEB-INF/views/market/marketDetailView.jsp
Final/src/main/webapp/WEB-INF/views/member/userOrderList.jsp

마켓메인 정렬시 품절 상품 'SOLDOUT' 표시되지 않는 이슈 해결

fix:[이정하] 마켓메인 품절 상품 ‘SOLDOUT’, 클래스메인 ‘오픈 전’ 표시 기능 구현[NOEL-72]

---

Final/src/main/java/com/kh/myapp/cl/model/vo/Review.java
Final/src/main/resources/mapper/classReviewSQL.xml
Final/src/main/webapp/WEB-INF/views/class/classDetail.jsp
Final/src/main/webapp/WEB-INF/views/class/classReviewAdd.jsp
Final/src/main/webapp/WEB-INF/views/class/classReviewDetail.jsp
Final/src/main/webapp/WEB-INF/views/class/classReviewUpdate.jsp

별점 라디오버튼 수정 시 수정된 값으로 저장되지 않는 이슈가 있습니다.

feat:[엄세연]클래스 리뷰에 별점 추가하고 수정 시 체크값 가져오기[NOEL-75]

---

Final/src/main/java/com/kh/myapp/cl/controller/ClassController.java
Final/src/main/webapp/WEB-INF/views/class/reserveList.jsp

bookName에 들어 있는 값을 가져와 className에 삽입

fix:[엄세연]클래스 리뷰 기능 구현[NOEL-61]

---

Final/src/main/java/com/kh/myapp/cl/model/service/ClassWishlistService.java
Final/src/main/java/com/kh/myapp/market/model/service/MarketWishService.java
Final/src/main/webapp/WEB-INF/views/class/myClassWishList.jsp
Final/src/main/webapp/WEB-INF/views/market/myPrdWishList.jsp
Final/src/main/webapp/WEB-INF/views/member/userOrderList.jsp
Final/src/main/webapp/resources/css/product/myWishList.css

1. 마켓 위시 페이징 수정
2. 클래스 위시 페이징 수정
3. 회원 > 마이페이지 > 구매평작성 버튼 UI 수정

fix: 일반회원 마켓 상품 상세페이지 ‘위시’, 마이페이지 ‘위시 모아보기' [NOEL-4]

---

Final/src/main/resources/mapper/classSQL.xml
Final/src/main/webapp/WEB-INF/views/class/classDetail.jsp
Final/src/main/webapp/WEB-INF/views/market/marketDetailView.jsp
Final/src/main/webapp/WEB-INF/views/market/memberQna.jsp

1.Javascript로 마켓 재고 수량만큼만 구매가능하게 변경
2.Javascript로 클래스 최대인원 만큼만 예약가능하게 변경

feat:[차현오]마켓 재고 수량만큼만 구매가능,클래스 최대인원 만큼만 예약가능[NOEL-78]

---

Final/src/main/java/com/kh/myapp/member/controller/MemberController.java
Final/src/main/java/com/kh/myapp/order/model/vo/OrderVO.java
Final/src/main/resources/mapper/marketSQL.xml
Final/src/main/resources/mapper/orderSQL.xml
Final/src/main/webapp/WEB-INF/views/member/userOrderList.jsp

회원 주문내역에서 구매평이 작성된 경우 버튼이 '구매평 확인'으로 뜨고,
클릭시 해당 리뷰 상세 페이지로 이동하도록 수정

fix:[이정하] 회원 마이페이지 주문내역에 구매평 작성 버튼 활성화[NOEL-45]

---

Final/src/main/java/com/kh/myapp/member/controller/MemberController.java
Final/src/main/java/com/kh/myapp/member/model/service/MemberService.java
Final/src/main/webapp/WEB-INF/views/member/marketerClassQna.jsp

fix:[차현오]판매자 마이페이지 마켓,클래스 qna관리[NOEL-80]

---

Final/src/main/webapp/WEB-INF/views/class/myClassWishList.jsp
Final/src/main/webapp/WEB-INF/views/market/myPrdWishList.jsp
Final/src/main/webapp/WEB-INF/views/member/memberClassQna.jsp
Final/src/main/webapp/WEB-INF/views/member/memberQna.jsp

1. 회원 > 마이페이지 > 마켓 & 클래스 QNA UI 수정
2. 회원 > 마이페이지 > 마켓 & 클래스 위시 UI 수정

design:[이정하] 회원 마이페이지에서 본인이 작성한 qna만 출력[NOEL-53]

---

Final/src/main/webapp/WEB-INF/views/class/classDetail.jsp
Final/src/main/webapp/WEB-INF/views/class/classReviewAdd.jsp

fix:[엄세연]클래스 파트 css 및 ui 조정[NOEL-71]
